import { nanoid } from "nanoid";
import type { Memo } from "../api/data-contracts";
import type { DB } from ".";

export const memosSeed: Memo[] = [
  {
    id: nanoid(),
    title: "Project Kickoff",
    description: "Initial meeting notes for project start",
    content: "Discussed timeline, goals, and team responsibilities.",
    tags: ["meeting", "project"],
    createdAt: new Date("2025-07-01T09:00:00Z"),
    updatedAt: new Date("2025-07-01T09:00:00Z"),
  },
  {
    id: nanoid(),
    title: "UI Design Review",
    description: "Feedback and decisions on UI mockups",
    content: "Accepted most of the design, need changes on navigation flow.",
    tags: ["design", "ui"],
    createdAt: new Date("2025-07-03T11:30:00Z"),
    updatedAt: new Date("2025-07-03T13:00:00Z"),
  },
  {
    id: nanoid(),
    title: "Weekly Sync - July Week 1",
    description: "Team weekly update",
    content: "All team members are on track. Minor blockers on backend side.",
    tags: ["weekly", "update"],
    createdAt: new Date("2025-07-05T10:00:00Z"),
    updatedAt: new Date("2025-07-05T10:00:00Z"),
  },
  {
    id: nanoid(),
    title: "Bug Report - Auth Failure",
    description: "Login fails under specific conditions",
    content: "When user inputs invalid token twice, the session breaks.",
    tags: ["bug", "auth"],
    createdAt: new Date("2025-07-06T14:45:00Z"),
    updatedAt: new Date("2025-07-06T15:10:00Z"),
  },
  {
    id: nanoid(),
    title: "Content Strategy Notes",
    description: "Ideas for Q3 content roadmap",
    content: "Focus on tutorials, user success stories, and documentation.",
    tags: ["content", "strategy"],
    createdAt: new Date("2025-07-07T16:00:00Z"),
    updatedAt: new Date("2025-07-07T16:00:00Z"),
  },
  {
    id: nanoid(),
    title: "Sprint Retrospective",
    description: "Team feedback from sprint 12",
    content: "Improve daily standup structure, celebrate wins more.",
    tags: ["sprint", "retrospective"],
    createdAt: new Date("2025-07-08T12:00:00Z"),
    updatedAt: new Date("2025-07-08T12:30:00Z"),
  },
  {
    id: nanoid(),
    title: "Tech Debt List",
    description: "Backlog of technical debt items",
    content: "Refactor auth service, update legacy API endpoints.",
    tags: ["techdebt"],
    createdAt: new Date("2025-07-10T10:00:00Z"),
    updatedAt: new Date("2025-07-10T10:00:00Z"),
  },
  {
    id: nanoid(),
    title: "Customer Feedback Summary",
    description: "Compiled feedback from June",
    content: "Users request dark mode, faster load time, and mobile fixes.",
    tags: ["feedback"],
    createdAt: new Date("2025-07-11T09:30:00Z"),
    updatedAt: new Date("2025-07-11T09:30:00Z"),
  },
  {
    id: nanoid(),
    title: "API Docs Plan",
    description: "Outline for upcoming API documentation overhaul",
    content: "Group by functionality, add examples and use cases.",
    tags: ["docs", "api"],
    createdAt: new Date("2025-07-12T15:00:00Z"),
    updatedAt: new Date("2025-07-12T15:00:00Z"),
  },
  {
    id: nanoid(),
    title: "Release Notes v1.4",
    description: "Summary of features and bug fixes",
    content: "New dashboard, fixed logout issue, improved performance.",
    tags: ["release"],
    createdAt: new Date("2025-07-14T10:00:00Z"),
    updatedAt: new Date("2025-07-14T10:30:00Z"),
  },
  {
    id: nanoid(),
    title: "Team Offsite Planning",
    description: "Prep notes for Q3 team offsite",
    content: "Suggest beach or mountain location, finalize budget.",
    tags: ["team", "planning"],
    createdAt: new Date("2025-07-15T14:00:00Z"),
    updatedAt: new Date("2025-07-15T14:00:00Z"),
  },
  {
    id: nanoid(),
    title: "Database Optimization",
    description: "Indexes and query performance",
    content: "Added indexes to users table, reduced query time by 40%.",
    tags: ["db", "performance"],
    createdAt: new Date("2025-07-16T13:00:00Z"),
    updatedAt: new Date("2025-07-16T13:30:00Z"),
  },
  {
    id: nanoid(),
    title: "User Onboarding Flow",
    description: "Draft plan for improved onboarding",
    content: "Introduce guided tour and task-based introduction.",
    tags: ["ux", "onboarding"],
    createdAt: new Date("2025-07-17T11:00:00Z"),
    updatedAt: new Date("2025-07-17T11:00:00Z"),
  },
  {
    id: nanoid(),
    title: "Incident Report - July 18",
    description: "Postmortem of production outage",
    content: "Caused by bad deployment script, fixed with hotpatch.",
    tags: ["incident", "postmortem"],
    createdAt: new Date("2025-07-18T16:00:00Z"),
    updatedAt: new Date("2025-07-18T17:00:00Z"),
  },
  {
    id: nanoid(),
    title: "Hiring Plan H2",
    description: "Roles and timeline for next 6 months",
    content: "2 engineers, 1 designer, 1 product manager needed.",
    tags: ["hr", "hiring"],
    createdAt: new Date("2025-07-19T12:30:00Z"),
    updatedAt: new Date("2025-07-19T12:30:00Z"),
  },
  {
    id: nanoid(),
    title: "Product Roadmap Q4",
    description: "Feature priorities and milestones",
    content: "Focus on stability, analytics, and partner integrations.",
    tags: ["product", "roadmap"],
    createdAt: new Date("2025-07-20T10:00:00Z"),
    updatedAt: new Date("2025-07-20T10:00:00Z"),
  },
  {
    id: nanoid(),
    title: "Marketing Campaign Results",
    description: "Email campaign A/B test results",
    content: "Version B had 25% higher open rate. Use it going forward.",
    tags: ["marketing"],
    createdAt: new Date("2025-07-21T08:00:00Z"),
    updatedAt: new Date("2025-07-21T08:00:00Z"),
  },
  {
    id: nanoid(),
    title: "Q2 Financial Report",
    description: "Summary of revenues and expenses",
    content: "Revenue up by 10%, main expense was infrastructure.",
    tags: ["finance"],
    createdAt: new Date("2025-07-22T13:00:00Z"),
    updatedAt: new Date("2025-07-22T13:00:00Z"),
  },
  {
    id: nanoid(),
    title: "Security Audit Findings",
    description: "Issues from external audit",
    content: "Rotate credentials, patch XSS vulnerability in comments.",
    tags: ["security", "audit"],
    createdAt: new Date("2025-07-23T15:30:00Z"),
    updatedAt: new Date("2025-07-23T15:45:00Z"),
  },
  {
    id: nanoid(),
    title: "Learning Resources",
    description: "Recommended courses for engineers",
    content: "React, GraphQL, and advanced TypeScript recommended.",
    tags: ["learning", "training"],
    createdAt: new Date("2025-07-24T09:00:00Z"),
    updatedAt: new Date("2025-07-24T09:00:00Z"),
  },
  {
    id: nanoid(),
    title: "Team Survey Results",
    description: "Internal team happiness survey",
    content: "High satisfaction, request more remote days.",
    tags: ["team", "survey"],
    createdAt: new Date("2025-07-25T11:30:00Z"),
    updatedAt: new Date("2025-07-25T11:30:00Z"),
  },
  {
    id: nanoid(),
    title: "Code Review Guidelines",
    description: "Best practices for code reviews",
    content: "Check for readability, test coverage, and logic clarity.",
    tags: ["engineering", "code"],
    createdAt: new Date("2025-07-26T10:00:00Z"),
    updatedAt: new Date("2025-07-26T10:00:00Z"),
  },
  {
    id: nanoid(),
    title: "OKRs Planning",
    description: "Draft of Q3 OKRs",
    content: "Focus on feature delivery, uptime, and support metrics.",
    tags: ["okr", "planning"],
    createdAt: new Date("2025-07-27T12:00:00Z"),
    updatedAt: new Date("2025-07-27T12:00:00Z"),
  },
  {
    id: nanoid(),
    title: "Partner Integration Notes",
    description: "Notes from call with new partner",
    content: "Integration via OAuth, sandbox access next week.",
    tags: ["partner", "integration"],
    createdAt: new Date("2025-07-28T14:30:00Z"),
    updatedAt: new Date("2025-07-28T14:30:00Z"),
  },
  {
    id: nanoid(),
    title: "Legal Review",
    description: "Checklist before contract signing",
    content: "Data processing clauses and SLA compliance reviewed.",
    tags: ["legal"],
    createdAt: new Date("2025-07-29T10:00:00Z"),
    updatedAt: new Date("2025-07-29T10:00:00Z"),
  },
  {
    id: nanoid(),
    title: "App Performance Testing",
    description: "Load test results summary",
    content: "Handled 5K concurrent users, minor latency spikes.",
    tags: ["testing", "performance"],
    createdAt: new Date("2025-07-30T15:00:00Z"),
    updatedAt: new Date("2025-07-30T15:00:00Z"),
  },
  {
    id: nanoid(),
    title: "Feature Backlog Grooming",
    description: "Cleaned up backlog, assigned priorities",
    content: "Removed duplicates, clarified specs.",
    createdAt: new Date("2025-08-01T10:30:00Z"),
    updatedAt: new Date("2025-08-01T10:30:00Z"),
  },
  {
    id: nanoid(),
    title: "Accessibility Improvements",
    description: "Audit and fix plan for accessibility",
    content: "Add ARIA labels, improve contrast, test screen reader.",
    tags: ["accessibility"],
    createdAt: new Date("2025-08-03T09:00:00Z"),
    updatedAt: new Date("2025-08-03T09:00:00Z"),
  },
  {
    id: nanoid(),
    title: "Internal FAQ",
    description: "Answers to common internal questions",
    content: "Deployment steps, support contacts, time-off policy.",
    createdAt: new Date("2025-08-05T08:00:00Z"),
    updatedAt: new Date("2025-08-05T08:00:00Z"),
  },
  {
    id: nanoid(),
    title: "Final Memo",
    description: "Placeholder for 30th memo",
    content: "Final memo content goes here.",
    tags: [],
    createdAt: new Date("2025-08-06T11:00:00Z"),
    updatedAt: new Date("2025-08-06T11:00:00Z"),
  },
];

export async function seedDatabase(db: DB): Promise<void> {
  const count = await db.memos.count();
  if (count > 0) {
    return;
  }
  await db.memos.bulkAdd(memosSeed);
}
